#!/bin/bash

#s*****************************************************************************
#s*
#s* SHELL FILENAME : getArchive
#s*
#s* ROLE :  Restaure un package de l'archives
#s*
#s* AUTEUR : V. Cephirins (AKKA)
#s* PARAMETRES :
#s* SYNOPSIS :
#s*
#s* VERSION : 1.0  Creation
#s* VERSION : 1.1  Ajout de deepArchives
#s*****************************************************************************

. utils.bash

package=$(basename ${1%.tar.gz}).tar.gz

# interdit la restauration de certains packages
prefixTool=${package%_[vV][0-9]*}
if [[ "${prefixTool}" == "VDLIB_SERVER" ||
      "${prefixTool}" == "utils" ]]
then
   echo "administrator privileges required !" >&2
else
   if [[ -f "$VDLIB_PATH/archives/${package}" ]]
   then
      cp $VDLIB_PATH/archives/${package} $VDLIB_PATH/livraison/${package}.restore
      chmod o+rw $VDLIB_PATH/livraison/${package}.restore
      echo "$VDLIB_PATH/livraison/${package}.restore"
   else
      if [[ -f "$VDLIB_PATH/deepArchives/${package}" ]]
      then
         cp $VDLIB_PATH/deepArchives/${package} $VDLIB_PATH/livraison/${package}.restore
         chmod o+rw $VDLIB_PATH/livraison/${package}.restore
         echo "$VDLIB_PATH/livraison/${package}.restore"
      else
         echo "package '${package}' not found !" >&2
      fi;
   fi;
fi;

