--MOD 148
--select 'INSERT INTO LA00_PARAM (PARAM_LOG_LINE_NO, PARAM_LABEL, PARAM_VALUE ) 
--   VALUES ('''||PARAM_LOG_LINE_NO||''','''||PARAM_LABEL||''','''||PARAM_VALUE||''');'
--FROM LA00_PARAM where PARAM_LABEL LIKE 'COSACHK_%' ORDER BY 1; 

--MOD 133
--select 'INSERT INTO LA00_PARAM (PARAM_LOG_LINE_NO, PARAM_LABEL, PARAM_VALUE )
--   VALUES ('''||PARAM_LOG_LINE_NO||''','''||PARAM_LABEL||''','''||PARAM_VALUE||''');'
--FROM LA00_PARAM where PARAM_LABEL LIKE 'SESAMEHK_%' ORDER BY 1; 

--MOD 163
select 'INSERT INTO LA00_TCU_PARAM 
   (ID_TCU_PARAM_NO, ID_TCU_UNIT_NO, TCU_PARAM_LB, 
    TCU_PARAM_TYP_NB, TCU_PARAM_POS_NB, T CU_PARAM_FREQ_NB)
   VALUES ('''||ID_TCU_PARAM_NO||''','''||ID_TCU_UNIT_NO||''','''||TCU_PARAM_LB||''','''||TCU_PARAM_TYP_NB||''','''||TCU_PARAM_POS_NB||''','''||TCU_PARAM_FREQ_NB||''');' 
FROM LA00_TCu_PARAM WHERE ID_TCU_PARAM_NO BETWEEN '80' AND '91' ORDER BY 1;

